name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
          cache: true

      - name: Install dependencies
        working-directory: user-service
        run: go mod download && go mod verify

      - name: Run go vet
        working-directory: user-service
        run: go vet ./...

      - name: Check formatting
        working-directory: user-service
        run: |
          test -z $(gofmt -l .)

      - name: Run tests
        working-directory: user-service
        run: go test -v -race ./...

      - name: Build
        working-directory: user-service
        run: go build -v ./cmd/main.go