name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.25.x]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: |
        cd user-service
        go mod download
        go mod verify

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.57.2
        working-directory: user-service
        args: --timeout=5m

    - name: Build
      working-directory: user-service
      run: go build -v ./cmd/main.go

    - name: Run tests
      working-directory: user-service
      run: go test -v -race ./...