name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          cd user-service
          go mod download
          go mod verify

      - name: Run go vet
        run: |
          cd user-service
          go vet ./...

      - name: Check formatting
        run: |
          cd user-service
          test -z $(gofmt -l .)

      - name: Run tests
        run: |
          cd user-service
          go test -v -race ./...

      - name: Build
        run: |
          cd user-service
          go build -v ./cmd/main.go