# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install and run golangci-lint
      run: |
        set -eux
        mkdir -p $GITHUB_WORKSPACE/bin /tmp/golangci
        curl -sSL -o /tmp/golangci/golangci.tgz "https://github.com/golangci/golangci-lint/releases/download/v1.58.0/golangci-lint-1.58.0-linux-amd64.tar.gz"
        tar -xzf /tmp/golangci/golangci.tgz -C /tmp/golangci
        mv /tmp/golangci/golangci-lint-1.58.0-linux-amd64/golangci-lint $GITHUB_WORKSPACE/bin/
        export PATH="$GITHUB_WORKSPACE/bin:$PATH"
        # Clean go build cache and module cache to avoid loading incompatible export data
        go clean -cache -modcache || true
        golangci-lint run --out-format=github-actions --timeout 5m
      working-directory: ./server/user-service

    - name: Build
      working-directory: ./server/user-service
      run: go build -v ./...

    - name: Test
      working-directory: ./server/user-service
      run: go test -v ./...
